CREATE DATABASE AIT580_PROJECT4;

USE AIT580_PROJECT4;

CREATE TABLE DEVELOPMENT_DATA (
S_NO INTEGER,
SQ_FOOTAGE INTEGER,
PROJ_TYPE VARCHAR(50),
ROOMS INTEGER,
APP_TYPE VARCHAR(10),
PROJ_NAME VARCHAR(50),
CATEGORY_ VARCHAR(20),
CRE_YEAR VARCHAR(10),
LAST_YEAR INTEGER,
BOZA VARCHAR(15),
PC VARCHAR(30),
LDT VARCHAR(20),
DRC VARCHAR(20)
);

LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/Cleaned_Development_data.csv' INTO TABLE DEVELOPMENT_DATA FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\r\n' IGNORE 1 ROWS;

SELECT * FROM DEVELOPMENT_DATA LIMIT 10;

--1. How many number of projects are there per Project type?

SELECT PROJ_TYPE, COUNT(PROJ_TYPE) AS NUMBER_OF_PROJECTS FROM DEVELOPMENT_DATA GROUP BY PROJ_TYPE ORDER BY NUMBER_OF_PROJECTS DESC;

--2. Identify the number of projects per Application Type and Category.

SELECT APP_TYPE, PROJ_TYPE, COUNT(PROJ_TYPE) AS NUMBER_OF_PROJECTS FROM DEVELOPMENT_DATA GROUP BY APP_TYPE ORDER BY NUMBER_OF_PROJECTS DESC;

SELECT CATEGORY_, PROJ_TYPE, COUNT(PROJ_TYPE) AS NUMBER_OF_PROJECTS FROM DEVELOPMENT_DATA GROUP BY CATEGORY_ ORDER BY NUMBER_OF_PROJECTS DESC;

--3. Which category and Application Type have the highest number of projects?

SELECT APP_TYPE, PROJ_TYPE, COUNT(PROJ_TYPE) AS NUMBER_OF_PROJECTS FROM DEVELOPMENT_DATA GROUP BY APP_TYPE ORDER BY NUMBER_OF_PROJECTS DESC LIMIT 1; 

SELECT CATEGORY_, PROJ_TYPE, COUNT(PROJ_TYPE) AS NUMBER_OF_PROJECTS FROM DEVELOPMENT_DATA GROUP BY CATEGORY_ ORDER BY NUMBER_OF_PROJECTS DESC LIMIT 1;

--4. List and count of projects that are hospitals.

SELECT PROJ_NAME FROM DEVELOPMENT_DATA WHERE PROJ_NAME LIKE '%HOSPITAL%';

SELECT COUNT(PROJ_NAME) FROM DEVELOPMENT_DATA WHERE PROJ_NAME LIKE '%HOSPITAL%';

--6. Which project has highest square footage and highest number of rooms?

SELECT PROJ_NAME, SQ_FOOTAGE FROM DEVELOPMENT_DATA ORDER BY SQ_FOOTAGE DESC LIMIT 1;

SELECT PROJ_NAME, ROOMS FROM DEVELOPMENT_DATA ORDER BY ROOMS DESC LIMIT 1;

--7. How many projects are proposed to be built on a highway?

SELECT PROJ_NAME FROM DEVELOPMENT_DATA WHERE PROJ_NAME LIKE '%HIGHWAY%'; 

SELECT COUNT(PROJ_NAME) FROM DEVELOPMENT_DATA WHERE PROJ_NAME LIKE '%HIGHWAY%'; 

-- 9.What proportion of projects have received the required approval of construction from the appropriate Boards/ Committees?

SELECT COUNT(*) FROM DEVELOPMENT_DATA;

SELECT BOZA, COUNT(BOZA) FROM DEVELOPMENT_DATA GROUP BY BOZA;

SELECT PC, COUNT(PC) FROM DEVELOPMENT_DATA GROUP BY PC;

SELECT LDT, COUNT(LDT) FROM DEVELOPMENT_DATA GROUP BY LDT;

SELECT DRC, COUNT(DRC) FROM DEVELOPMENT_DATA GROUP BY DRC;







